### ISSUE TITLE
Сползло вниз боковое меню

### ISSUE THREAD

**Issue by Topinambur223606** [mrAntiUser/JRAS#81]
На главной панель справа с разделами, тегами и пр. сползает вниз, если в секции настроек JRAS "Стиль" выбрана опция "Корректировать дизайн и стиль сайта". Дочерние настройки в этом пункте на это поведение никак не влияют (к примеру, сокрытие правого меню и его выдвижение работает, но внизу страницы).
![Гифка](https://user-images.githubusercontent.com/37106409/64479911-c330dd00-d1c6-11e9-80d1-4c14cbcf1d15.gif)

**Comment by mrAntiUser** [comment]
> На главной панель справа с разделами, тегами и пр. сползает вниз, если в секции настроек JRAS "Стиль" выбрана опция "Корректировать дизайн и стиль сайта".

А если потом перегрузить страницу?

**Comment by Topinambur223606** [comment]
Тогда перезагружал много раз, с разными настройками, ничего не менялось.
А сейчас, к слову, баг пропал, как его воспроизвести - не знаю; так что, наверное, можно закрывать.

**Comment by mrAntiUser** [comment]
Там koka со стилями мутил, когда делал почту "нормальную", может он чего поломал, ну и зачинил потом.
